{% set name = "gwsumm" %}
{% set version = "1.0.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "815b0db0d4b3b9258f9dea6b78eb61b245a9f0f3df084c7d5d5cb4d0aa0b6824"

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"
  skip: true  # [win]

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - astropy >=1.2.1
    - gwdatafind
    - gwdetchar >=1.0.0
    - gwpy >=1.0.0
    - gwtrigfind
    - lscsoft-glue >=1.60.0
    - ligo-segments
    - lxml
    - markdown
    - markuppy
    - matplotlib-base >=2.0.0
    - numpy >=1.16
    - pygments
    - python-dateutil
    - python-lal >=6.19.0
    - scipy >=1.2.0

test:
  requires:
    - pytest >=2.8,<3.7
  imports:
    - gwsumm
    - gwsumm.archive
    - gwsumm.channels
    - gwsumm.config
    - gwsumm.data
    - gwsumm.data.coherence
    - gwsumm.data.mathutils
    - gwsumm.data.range
    - gwsumm.data.spectral
    - gwsumm.data.timeseries
    - gwsumm.data.utils
    - gwsumm.globalv
    - gwsumm.html
    - gwsumm.html.bootstrap
    - gwsumm.html.html5
    - gwsumm.html.static
    - gwsumm.io
    - gwsumm.mode
    - gwsumm.segments
    - gwsumm.state
    - gwsumm.state.all
    - gwsumm.state.registry
    - gwsumm.triggers
    - gwsumm.units
    - gwsumm.utils
  commands:
    # run unit tests (skip error on osx)
    - python -m pytest --pyargs {{ name }}  # [not osx]
    - python -m pytest --pyargs {{ name }} -k 'not test_finalize'  # [osx]
    # check scripts run ok
    - gw_summary --help
    - gw_summary day --help
    - gw_summary week --help
    - gw_summary month --help
    - gw_summary gps --help
    - gw_summary_pipe --help
    - gwsumm-plot-guardian --help
    - gwsumm-plot-triggers --help

about:
  home: "https://github.com/gwpy/gwsumm"
  doc_url: "https://gwsumm.readthedocs.io/en/latest/"
  dev_url: "https://github.com/gwpy/gwsumm"
  license: "GPL-3.0-or-later"
  license_family: "GPL"
  license_file: "LICENSE"
  summary: "Gravitational-wave interferometer summary information system"
  description: |
    GWSumm is a python toolbox used by the LIGO Scientific Collaboration to
    summarise and archive sundry facets of the performance of the LIGO
    instruments, and archive these data in a nested HTML structure.

extra:
  recipe-maintainers:
    - alurban
    - duncanmmacleod
