{% set name = "gwsumm" %}
{% set version = "2.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 609de1d83147ea65ae921d80faa4f9d4e815f2cdbefa3d0d790fbf834e189795
  patches:
    # see https://github.com/gwpy/gwsumm/compare/2.2.0...duncanmmacleod:gwsumm:conda-patches?expand=1
    # to update:
    #   - checkout the duncanmmacleod/gwsumm@conda-patches branch
    #   - fetch the latest tag from gwpy/gwsumm
    #   - rebase against the new tag: `git rebase <tag>`
    #   - resolve any conflicts
    #   - if conflicts, or any new patches needed,
    #     (re)create the new patch files: `git format-patch <tag>`
    - 0001-pyproject.toml-remove-lalsuite-from-dependencies.patch

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - gw_summary = gwsumm.__main__:main
    - gw_summary_pipe = gwsumm.batch:main
    - gwsumm-plot-guardian = gwsumm.plot.guardian.__main__:main
    - gwsumm-plot-triggers = gwsumm.plot.triggers.__main__:main

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=61
  run:
    - astropy >=3.0.0
    - gwdatafind >=1.1.1
    - gwdetchar >=2.2.7
    - gwpy >=3.0.9
    - gwtrigfind
    - lscsoft-glue >=1.60.0
    - lxml
    - markdown
    - markuppy
    - matplotlib >=3.5.0
    - numpy >=1.16
    - pygments >=2.7.0
    - python >={{ python_min }}
    - python-dateutil
    - python-lal >=6.19.0
    - python-ligo-lw
    - scipy >=1.2.0

test:
  requires:
    - flake8
    - pip
    - pytest >=3.3.0
    - pytest-cov >=2.4.0
    - python {{ python_min }}
  imports:
    - gwsumm
    - gwsumm.archive
    - gwsumm.channels
    - gwsumm.config
    - gwsumm.data
    - gwsumm.data.coherence
    - gwsumm.data.mathutils
    - gwsumm.data.range
    - gwsumm.data.spectral
    - gwsumm.data.timeseries
    - gwsumm.data.utils
    - gwsumm.globalv
    - gwsumm.html
    - gwsumm.html.bootstrap
    - gwsumm.html.html5
    - gwsumm.html.static
    - gwsumm.io
    - gwsumm.mode
    - gwsumm.segments
    - gwsumm.state
    - gwsumm.state.all
    - gwsumm.state.registry
    - gwsumm.triggers
    - gwsumm.units
    - gwsumm.utils
  commands:
    # check requirements
    - python -m pip check
    # run unit tests
    - python -m pytest --pyargs {{ name }}
    # check scripts run ok
    - python -m gwsumm --help
    - python -m gwsumm day --help
    - python -m gwsumm week --help
    - python -m gwsumm month --help
    - python -m gwsumm gps --help
    - python -m gwsumm.batch --help
    - python -m gwsumm.plot.guardian --help
    - python -m gwsumm.plot.triggers --help
    # check entry points
    - gw_summary --help
    - gw_summary_pipe --help
    - gwsumm-plot-guardian --help
    - gwsumm-plot-triggers --help

about:
  home: https://github.com/gwpy/gwsumm
  doc_url: https://gwsumm.readthedocs.io/en/latest/
  dev_url: https://github.com/gwpy/gwsumm
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Gravitational-wave interferometer summary information system
  description: |
    GWSumm is a python toolbox used by the LIGO Scientific Collaboration to
    summarise and archive sundry facets of the performance of the LIGO
    instruments, and archive these data in a nested HTML structure.

extra:
  recipe-maintainers:
    - alurban
    - areeda
    - duncanmmacleod
    - eagoetz
    - robertbruntz
    - iaraota
